### ISSUE TITLE
Demo in README just shows a 404

### ISSUE THREAD

**Issue by CelestialStreamer** [YunYouJun/hexo-widget-tree#10]
### Describe the bug

The readme contains a link to a demo site, yet the page just displays a 404 page, not showcasing any widget-tree example.

### Reproduction

Live in the USA maybe?

### System Info

```Shell
N/A
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
OK, let's see it here: https://hexo-theme-yun.yunyoujun.cn/posts/widget-tree/
