### ISSUE TITLE
[enhancement] page页面建议能展开对应文章的树形菜单目录，并且高亮该文章项

### ISSUE THREAD

**Issue by jianchengwang** [YunYouJun/hexo-widget-tree#2]
试了下，感觉很不错，就有个小建议，如题，以下是截图
![image](https://user-images.githubusercontent.com/15951975/95570053-f7756d80-0a58-11eb-8a9a-75b937714d93.png)
另外就是看要不要适配夜间模式了

**Comment by YunYouJun** [comment]
每篇文章目录加上文章分类、文章数据量还是挺大的，我打算加个配置项自由决定是否显示目录吧。

至于夜间模式……，肯定得鸽挺久的，没啥时间一直整这个，有空再继续完善。

**Comment by YunYouJun** [comment]
文章目录功能已经加上了。使用见文档，可配置是否开启，最大最小深度及是否显示序号。

高亮的话咱只高亮了打开的图标，因为文章标题也是一个链接，有对应的 hover 的颜色，所以就不加在标题上了。

文章有目录则显示可扩展的图标，没有目录则直接显示文章图标。

**Comment by jianchengwang** [comment]
> 文章目录功能已经加上了。使用见文档，可配置是否开启，最大最小深度及是否显示序号。
> 
> 高亮的话咱只高亮了打开的图标，因为文章标题也是一个链接，有对应的 hover 的颜色，所以就不加在标题上了。
> 
> 文章有目录则显示可扩展的图标，没有目录则直接显示文章图标。

呃呃呃，可能我的表达有问题，大佬理解错了，我的意思是文章详情页面的话，该文章所在的目录可以自动展开，并且该文章的菜单项高亮显示，而不是把toc嵌套在目录里面，因为toc本来就有了。不过toc嵌套在目录里面感觉也挺实用的，不需要把目录折叠起来，然后再看自带主题的toc，减少操作。
现在文章详情页，目录默认都是折叠的，如图所示
![image](https://user-images.githubusercontent.com/15951975/95603215-8baaf900-0a88-11eb-8b45-23d08cfd7f29.png)
想要的效果如下，
![image](https://user-images.githubusercontent.com/15951975/95603358-bd23c480-0a88-11eb-8b7b-1b38b3051bbf.png)
这样主要是方便查阅把，不用再手动找到文章的目录，然后再展开，一般树控件都是这样的，子菜单项选中，父菜单展开，
![image](https://user-images.githubusercontent.com/15951975/95604051-b3e72780-0a89-11eb-996e-259382b48936.png)

**Comment by YunYouJun** [comment]
其实就是指根据文章显示对应在树状菜单中的位置吧。
菜单项高亮是指啥……

**Comment by jianchengwang** [comment]
> 其实就是指根据文章显示对应在树状菜单中的位置吧。
> 菜单项高亮是指啥……

对的，高亮就是树状菜单里的这篇文章高亮呀。。表示当前这篇文章选中了呀，当前页面展示的是这篇文章

**Comment by YunYouJun** [comment]
……我还以为指啥特殊菜单

等我明天再整🐦。

**Comment by YunYouJun** [comment]
整好了。

**Comment by jianchengwang** [comment]
> 整好了。

嗯，试了下，效果不错，大佬牛批
