### ISSUE TITLE
大佬支持多级目录吗

### ISSUE THREAD

**Issue by Brannua** [YunYouJun/hexo-widget-tree#8]
大佬请问这个插件支持这样的多级目录吗，还是文件夹只能平铺 ？
![image](https://user-images.githubusercontent.com/38487617/135719429-4e7fcbad-928f-489a-b195-81bfbc136f20.png)

**Comment by Brannua** [comment]
啊，我开了 hotreload 以为可以实时预览，没想到不行。。重启了服务就好了。。关了关了，大佬牛皮

**Comment by Brannua** [comment]
npm 插件可以 hotreload 吗，在本地开发模式下

**Comment by YunYouJun** [comment]
这倒不是 npm 的问题，这是 hexo 太陈旧了，很多开发体验跟不上，这些问题没法解决。

**Comment by Brannua** [comment]
> 这倒不是 npm 的问题，这是 hexo 太陈旧了，很多开发体验跟不上，这些问题没法解决。

大佬你是怎么知道这是 hexo 陈旧的问题，是看了文档吗 ？

**Comment by YunYouJun** [comment]
🤣 hexo 本身都是原生的 js 写的，包括插件的应用机制是静态生成 js 再插入，和现在的 Vue / React 之类的机制不同，从 hexo 本身没有实现热加载，所以开发跟不上。

**Comment by Brannua** [comment]
> Vue / React 之类的机制不同

那  Vue / React 之类的是靠什么实现的热加载呢（打破我家锅问到底。。）

**Comment by YunYouJun** [comment]
见 https://vue-loader-v14.vuejs.org/zh-cn/features/hot-reload.html

hexo 没有组件的概念

**Comment by Brannua** [comment]
> 见 https://vue-loader-v14.vuejs.org/zh-cn/features/hot-reload.html
> 
> hexo 没有组件的概念

懂了！谢谢大佬！
