### ISSUE TITLE
[ bug report ] 亮暗模式的问题

### ISSUE THREAD

**Issue by Brannua** [YunYouJun/hexo-widget-tree#9]
插件版本为最新

首先站点的 mode 设置成了 auto，本地启动 hexo 博客服务后进行站点预览，此时将博客整体的亮暗开关调至亮色，然后将 _data/yun.yml 中的 mode 设置为 dark，重启服务，插件并没有随之改成暗色，但站点确实已经是暗色

![image](https://user-images.githubusercontent.com/38487617/135754029-1cdab9dd-898a-49fe-aae5-8bc33c6065ea.png)

**Comment by YunYouJun** [comment]
「插件并没有随之改成暗色」是什么意思？是指图标吗？如果直接设置为暗色，就不需要图标了吧。

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/135754256-3d2e490b-f7fb-47f9-baa2-c7c5a9b178c6.png)
![image](https://user-images.githubusercontent.com/25154432/135754261-5d577e7d-e89a-4e7c-9850-2c0b269cfb10.png)

我这边亮暗看起来是没问题的？

**Comment by Brannua** [comment]
> ![image](https://user-images.githubusercontent.com/25154432/135754256-3d2e490b-f7fb-47f9-baa2-c7c5a9b178c6.png) ![image](https://user-images.githubusercontent.com/25154432/135754261-5d577e7d-e89a-4e7c-9850-2c0b269cfb10.png)
> 
> 我这边亮暗看起来是没问题的？

要不大佬打开瞅瞅？=> [我的站点](https://brannua.github.io/)

**Comment by Brannua** [comment]
测试了好几次，本地起服务效果就是 ok 的，部署上去以后，插件是白的，代码块也是白的，代码块的复制按钮也没了，但是本地他就是好的。。大佬怎么破。。

**Comment by YunYouJun** [comment]
开了 CDN？把 CDN 关掉看看。

以及查看主题暗色 CSS 是否打包进去了。

**Comment by Brannua** [comment]
CDN ？站点应该是没特别配置 CDN 相关，用的默认，插件也是用的默认配置，需要具体怎么做吗 ？第二句这个怎么看哇

**Comment by YunYouJun** [comment]
部署之前，重新生成了吗？清一下本地缓存重新部署看看。

**Comment by Brannua** [comment]
> 部署之前，重新生成了吗？清一下本地缓存重新部署看看。

应该不需要吧，因为我就不是手动部署的，我是用的 githubActions 的 CICD 云端自动编译部署的

**Comment by Brannua** [comment]
> 部署之前，重新生成了吗？清一下本地缓存重新部署看看。

我搭建博客的过程总结在 [这里](https://brannua.github.io/2021/09/20/%E7%A7%91%E6%99%AE%E4%B8%8E%E5%AE%9E%E8%B7%B5/init/) 了，写得相当详细

**Comment by YunYouJun** [comment]
你先手动部署一次，排查问题呀。

**Comment by Brannua** [comment]
> 你先手动部署一次，排查问题呀。

okok

**Comment by Brannua** [comment]
> 你先手动部署一次，排查问题呀。

不太行呀，部署了三遍，打开 console 清空缓存硬性重加载也不行

**Comment by Brannua** [comment]
> 你先手动部署一次，排查问题呀。

问题解决了，谢谢大佬！

**Comment by YunYouJun** [comment]
什么原因？

**Comment by Brannua** [comment]
> 什么原因？

估计是和我之前直接修改主题 css 代码有关，clone 了一份新的主题代码，没事了。。下次外挂 css,谢谢大佬！
